version: '3.8'

services:
  sentiment_analysis:
    # Build the Docker image using the Dockerfile in the current directory
    build: 
      context: .
      dockerfile: Dockerfile
    # Run the sentiment analysis script
    command: python sentiment_analysis.py
    # Define environment variables for the container, if needed
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    # Allocate sufficient resources, if necessary (adjust as needed)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    # Specify that the container should restart on failure
    restart: on-failure
